
return (require 'Enum') {
    'gain_strength',
    'gain_iq',
    'gain_piety',
    'gain_vitality',
    'gain_agility',
    'gain_luck',
    'lose_strength',
    'lose_iq',
    'lose_piety',
    'lose_vitality',
    'lose_agility',
    'lose_luck',
    'rejuvenation',
    'aging',
    'to_samurai',
    'to_lord',
    'to_ninja',
    'gain_gold',
    'gain_exp',
    'lost',
    'cure',
    'gain_hp',
    'healall',
}
