local lust = require 'test.lust'
local describe, it, expect = lust.describe, lust.it, lust.expect

describe('requires', function ()
    it('src', function ()
        expect(require 'src').to.be.a('table')
    end)
    it('di', function ()
        expect(require 'di.container').to.be.a('table')
    end)
    it('entities', function ()
        expect(require 'entities').to.be.a('table')
    end)
    it('enums', function ()
        expect(require 'enums').to.be.a('table')
    end)
    it('Game', function ()
        expect(require 'Game').to.be.a('table')
    end)
    it('repository', function ()
        expect(require 'repository').to.be.a('table')
    end)
    it('scenes', function ()
        expect(require 'scenes').to.be.a('table')
    end)
    it('valueobjects', function ()
        expect(require 'valueobjects').to.be.a('table')
    end)
end)
