
return (require 'util').requirer(...) {
    'Age',
    'ArmorClass',
    'AttackTimeLevel',
    'Attribute',
    'CharacterRequirement',
    'Dice',
    'EquipmentModifier',
    'Following',
    'HitPoint',
    'NextLevel',
    'Possession',
    'Price',
    'SavingThrow',
    'SpecialPower',
    'Spellbook',
    'SpellLearnLevel',
    'SpellLevel',
    'SpellPoint',
    'Statistics',
    'Treasure',
    'Whereabouts',
}
